# Origin story

Here is a little story about the very start of the MLSN guidelines. It was in February 2012 that we came up with the MLSN name. We had been working on this for a while. Larry was preparing for the Bouyoucos Conference to be held in Philadelphia in May 2012, and he would present the first MLSN guidelines there.

Larry and I had been in discussion about soil testing and fertilizer recommendations since I was in graduate school. I was not comfortable with existing guidelines. And I thought the PACE Turf guidelines were too high. At the time I was looking at K to be 50 ppm or higher, P to be 35 ppm or higher, but I had not systematically tried to make a new set of guidelines. I didn't like the existing ones, I was using my own idiosyncratic method, and then Larry hit on the idea that became MLSN.

PACE Turf had thousands of samples (soil test data) from good-performing turf from their soil testing business. ATC had thousands of samples from good-performing turf from our soil testing business. All the samples were from Brookside Labs, and all used the same method. Could we make use of these data somehow to find new nutrient guidelines? So we started looking at the data, and making lots of calculations (described here), and that became the MLSN guidelines. But, we needed a name.

The best I could think of was "Turf Performance Requirement." I was always focused on how much we need to have good turf. I guess that would have been the TPR guidelines. Larry came up with the "Minimum Levels for Sustainable Nutrition," to emphasize that that this is a minimum amount. "We know higher levels are fine," he wrote to me in February 2012, and "reducing inputs is really the only reason" to have lower recommendations. We were both fine with MLSN as a name, so that's what we went with, although we have always kept a slightly different focus. I've focused on supplying just what the grass uses, and the MLSN approach does that, while making sense for the type of soils (sandy ones!) that grasses are grown in today. PACE Turf has that approach together with an emphasis on reduced inputs and costs compared to conventional guidelines. This collaborative approach on the MLSN guidelines has worked well, and has made sense to turfgrass managers all over the world.

But we did not necessarily think it would be this way. Larry signed off that e-mail from five years ago with this: "Thanks for working on this. I think we are going to make a valuable contribution, but, I have low hopes of widespread adoption." From those low hopes we started with, I am happy to see so many people around the world making use of, and getting the desired results, with the MLSN guidelines. And to see what I expect the long term result will be, which is getting the same or better turf conditions, with less cost, fewer inputs, and less mental effort focused on turfgrass nutrition. That frees a bit of one's mind to focus on other matters, and I hope, makes the job easier and more enjoyable.
