# *In statu quo*

Every now and then, someone raises the issue of MLSN vs. conventional guidelines, and suggests that sticking with the status quo may be preferable to using the MLSN guidelines.

I wrote an 8 page essay about this topic in 2014: [Turfgrass nutrient guidelines, peer review, and potassium](http://files.asianturfgrass.com/20140615_mlsn_k.pdf). You can find it (along with a lot of other material) in the [ATC Library](https://www.asianturfgrass.com/publication/), and I recommend taking a few minutes to read that if you are at all interested in some of the foundational issues behind this debate.

Of course, there may be better ways to make fertilizer recommendations for turfgrass than MLSN. But I don't think conventional guidelines are a better way.

I'll try to explain this with an example of potassium (K) fertilizer recommendations for 373 soil nutrient analyses conducted by ATC at Brookside Labs using the Mehlich 3 extractant. Why 373? These are all the samples from September 2018 to September 2019---a year of test results. These are soil samples from professionally-managed turf, from multiple countries and climates, growing a variety of grass species. I'll say that the soil nutrient levels, and the soil K levels in these soil samples, are representative of a lot of soil nutrient levels today.

The lowest K in these 373 samples was 14 ppm (mg/kg, meaning mg of K per kg of soil); the median K was 57 ppm and the mean was 78 ppm; the maximum K was 541 ppm.

What I have done is calculate a K fertilizer recommendation for the upcoming 12 months for each of these 373 samples. I've done that using three different methods. One is MLSN. One is the conventional SLAN guidelines as described by Carrow et al. in their 2004 GCM article. And one is skipping soil testing altogether, and making a fertilizer recommendation based on supplying the grass with all the K that is is expected to use, disregarding any soil supply of K. To make this simple, I'll discuss the median fertilizer recommendation for this set of 373 soils.

For the first example, I'll imagine I'm growing fine fescue at St. Andrews, and that I supply 5 g N/m^2^ for the year. In that case, I expect the grass to use 2.5 g K/m^2^. What's the median fertilizer recommendation that I'll make for that set of 373 soil samples, using the conventional (SLAN) guidelines, using MLSN, and using no soil testing whatsoever? With conventional guidelines, the median recommendation is 9 g K/m^2^ right now. That's to ensure the soil K at the start of this 12 month period gets to the lower end of the level at which "little or no crop response is expected from applying the particular nutrient." With MLSN, the median recommendation is 0 g K/m^2^. This matches pretty well with Jim Arthur's advice regarding K requirement. And with the approach in which I disregard soil testing, the median recommendation is 2.5 g K/m^2^.

For the second example, I calculated the fertilizer requirement for *Poa annua* in London, in which case I expect to apply about 16 g N/m^2^ and expect the K use to be 8 g/m^2^. The median recommendation from conventional guidelines is again 9 g K/m^2^, because that approach looks only at the soil and does not consider grass species or location. My MLSN calculation, based on *Poa annua* with a 16 g N supply in London, comes up with a median K recommendation of 5 g K/m^2^. And disregarding the soil, the recommendation is 8 g/m^2^, matching plant use.

For the third example, I calculated a fertilizer requirement for creeping bentgrass in Chicago, with an N supply of 12 g/m^2^ and expected K use of 6 g/m^2^. Now the conventional recommendation is again 9 g K/m^2^, MLSN is 3, and no soil testing is 6.

These first three examples all have the same result, in that MLSN recommends the lowest amount of K, no soil testing at all gets a recommendation a bit higher than MLSN, and the conventional SLAN guidelines give the highest recommendation.

The fourth example gives a different result, by looking at seashore paspalum in Bangkok. In this tropical climate, I expect to put 20 g N/m^2^ on this variety of grass, and seashore paspalum uses just as much K as N, so I expect use to be 20 g K/m^2^. Can you guess the conventional recommendation? Yes, it is 9 g K/m^2^ again, because it considers only the soil, and not the grass or its growth rate. The no soil testing approach gives a recommendation of 20 g N/m^2^, to match grass supply. And for this situation MLSN gives a higher recommendation than conventional guidelines, with the median MLSN recommendation at 17 g K/m^2^.

With these four examples, one can see that using conventional guidelines gets the same recommendation for every situation, which might be the best way to do it, but I doubt it. I don't want to apply 9 g K to fine fescue in St. Andrews, and I don't want to grow seashore paspalum in Bangkok with only 9 g K either. Not soil testing at all, and just applying what the grass uses, seems like a reasonable approach, although for each of these four examples this resupply of grass use recommendation gives a higher amount than does MLSN. I like the MLSN approach because it adjusts for the location and for the grass type and for the amount of soil nutrients and for the way the grass is managed. In that way the median fertilizer recommendation goes all the way from 0 g K for fescue in St. Andrews to 17 g K for the hypothetical situation in Bangkok.